print('Arde en tus ojos un misterio, virgen')
print('esquiva y compañera.')
print('No sé si es odio o es amor la lumbre')
print('inagotable de tu aliaba negra.')
print('Conmigo irás mientras proyecte sombra')
print('mi cuerpo y quede a mi sandalia arena.')
print('-¿Eres la sed o el agua en mi camino?-')
print('Dime, virgen esquiva y compañera.')